spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: warn
    io.netty: warn
    org.springframework: warn
management:
  endpoints:
    web:
      exposure:
        include: '*'
